/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author musta
 */
public class FormDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormDashboard.class.getName());

    /**
     * Creates new form FormDashboard
     */
    public FormDashboard() {
        initComponents();
        lblNamaUser.setText("Halo, " + FormLogin.namaPenggunaYangLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        lblNamaUser = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnBookZumba = new javax.swing.JButton();
        btnBookSpinning = new javax.swing.JButton();
        btnBookYoga = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setText("LOG OUT");
        btnLogout.setBorderPainted(false);
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 660, 100, 40));

        lblNamaUser.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        lblNamaUser.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaUser.setText("Profiles");
        getContentPane().add(lblNamaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 400, 70));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel2.setText("TODAY'S CLASSES");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 170, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("20 : 00");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 70, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Spinning                          Coach Budi");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 350, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Yoga Class                        Coach Sarah");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 350, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("16 : 00");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 70, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("18 : 30");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 70, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Zumba                             Coach Alex");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 350, 50));

        btnBookZumba.setText("BOOK");
        btnBookZumba.addActionListener(this::btnBookZumbaActionPerformed);
        jPanel1.add(btnBookZumba, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, -1, -1));

        btnBookSpinning.setText("BOOK");
        btnBookSpinning.addActionListener(this::btnBookSpinningActionPerformed);
        jPanel1.add(btnBookSpinning, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, -1, -1));

        btnBookYoga.setText("BOOK");
        btnBookYoga.addActionListener(this::btnBookYogaActionPerformed);
        jPanel1.add(btnBookYoga, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 840, 330));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/BARCODE.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 270, 220));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel9.setText("MEMBER  ACCESS CARD");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 200, -1));

        jLabel10.setText("Scan at the gate to enter");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 150, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, 310, 310));

        jLabel12.setFont(new java.awt.Font("Square721 BT", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Welcome Back");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 120, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 241, 26));
        jLabel13.setText("Membership: VIP Active");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 190, 20));

        jLabel14.setFont(new java.awt.Font("Kristen ITC", 3, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 51));
        jLabel14.setText("FitLifePro");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 30, 200, 80));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/potoprofil.png"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 40, 390));

        jButton1.setFont(new java.awt.Font("Kristen ITC", 3, 36)); // NOI18N
        jButton1.setText("AYO MULAI WORKOUT");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vidio dashboard.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuWorkout pilih = new MenuWorkout();
        pilih.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        TampilanAwal awal = new TampilanAwal();
        awal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBookYogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookYogaActionPerformed
        String namaMember = FormLogin.namaPenggunaYangLogin; 
    
        // Data spesifik untuk tombol ini (Yoga)
        String kelas = "Yoga Class";
        String pelatih = "Coach Sarah";
        String jam = "16:00";

        // Memanggil FormPembayaran dan melemparkan data-data di atas
        FormPembayaran formBayar = new FormPembayaran(namaMember, kelas, jam, pelatih);
        formBayar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBookYogaActionPerformed

    private void btnBookZumbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookZumbaActionPerformed
        String namaMember = FormLogin.namaPenggunaYangLogin; 
    
        // Data spesifik untuk tombol ini (Yoga)
        String kelas = "Zumba Class";
        String pelatih = "Coach Alex";
        String jam = "18:30";

        // Memanggil FormPembayaran dan melemparkan data-data di atas
        FormPembayaran formBayar = new FormPembayaran(namaMember, kelas, jam, pelatih);
        formBayar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBookZumbaActionPerformed

    private void btnBookSpinningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookSpinningActionPerformed
        String namaMember = FormLogin.namaPenggunaYangLogin; 
    
        // Data spesifik untuk tombol ini (Yoga)
        String kelas = "Spinning Class";
        String pelatih = "Coach Budi";
        String jam = "20:00";

        // Memanggil FormPembayaran dan melemparkan data-data di atas
        FormPembayaran formBayar = new FormPembayaran(namaMember, kelas, jam, pelatih);
        formBayar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBookSpinningActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookSpinning;
    private javax.swing.JButton btnBookYoga;
    private javax.swing.JButton btnBookZumba;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNamaUser;
    // End of variables declaration//GEN-END:variables
}
