/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author UsmanEffendi
 */
import java.sql.ResultSet;
 
public class FormLogin extends javax.swing.JFrame {
    public static int idUserYangLogin = 0;
    public static String namaPenggunaYangLogin = "";
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormLogin.class.getName());

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        setResizable(false); 
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        TxtLoginEmail = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        TxtLoginPassword = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<-");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 60, 70));

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("FitLifePro");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 170, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Log in to your account");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Please enter your email and password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lblEmail.setText("Email");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        TxtLoginEmail.addActionListener(this::TxtLoginEmailActionPerformed);
        jPanel1.add(TxtLoginEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 290, 40));

        lblPassword.setText("Password");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        TxtLoginPassword.addActionListener(this::TxtLoginPasswordActionPerformed);
        jPanel1.add(TxtLoginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 290, 40));

        jCheckBox1.setText("Remember me");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 102, 255));
        jLabel8.setText("Forgot");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setText("Log in");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 310, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtLoginEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLoginEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLoginEmailActionPerformed

    private void TxtLoginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLoginPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLoginPasswordActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        TampilanAwal awal = new TampilanAwal();
        awal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Ambil data dari inputan
    String email = TxtLoginEmail.getText().trim();
    String password = new String(TxtLoginPassword.getPassword()).trim();

    // 2. Validasi Form Kosong
    if (email.isEmpty() || password.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Email dan Password tidak boleh kosong!", 
            "Peringatan", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 3. Pengecekan Email dan Password ke Database
    try {
        java.sql.Connection conn = DatabaseConnection.getKoneksi();
        String sql = "SELECT * FROM members WHERE email = ? AND password = ?";
        java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
        
        pstmt.setString(1, email);
        pstmt.setString(2, password);
        
        // Jalankan pencarian
        java.sql.ResultSet rs = pstmt.executeQuery();
        
        // Pengecekan apakah data ditemukan
        if (rs.next()) {
            // Data ditemukan, baru sekarang kita bisa ambil isinya
            String namaUser = rs.getString("nama");
            double beratUser = rs.getDouble("berat");
            double tinggiUser = rs.getDouble("tinggi");

            // Simpan nama untuk dipakai di Form lain
            FormLogin.idUserYangLogin = rs.getInt("id_member");
            //namaPenggunaYangLogin = namaUser;
            FormLogin.namaPenggunaYangLogin = namaUser;
            // Penerapan OOP
            models.Pengguna userYangLogin = new models.MemberVIP(namaUser, email, beratUser, tinggiUser, "VIP-001");

            if (userYangLogin instanceof models.MemberVIP) {
                models.MemberVIP memberResmi = (models.MemberVIP) userYangLogin;
                
                memberResmi.sapaMember(); 
                memberResmi.tampilkanInfo();
                
                javax.swing.JOptionPane.showMessageDialog(this, "Login Berhasil, " + namaUser + "!");
                
                FormDashboard dashboard = new FormDashboard();
                dashboard.setVisible(true);
                this.dispose(); 
            }
            
        } else {
            // Jika tidak ditemukan
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Email atau Password salah!", 
                "Akses Ditolak", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error Database: " + e.getMessage(), 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtLoginEmail;
    private javax.swing.JPasswordField TxtLoginPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPassword;
    // End of variables declaration//GEN-END:variables
}
