/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author UsmanEffendi
 */
public class FormDetailWorkout extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormDetailWorkout.class.getName());

    /**
     * Creates new form FormDetailWorkout
     */
    public FormDetailWorkout() {
        initComponents();
    }

    // Method untuk menerima data jenis latihan dari halaman sebelumnya
    public void setJenisLatihan(String jenisOtot) {
        lblJudulLatihan.setText("Latihan Fokus: " + jenisOtot);
        
        // Logika penentuan gerakan
        switch (jenisOtot) {
            case "Dada" -> lblDetailGerakan.setText("<html>Gerakan:<br>1. Push Up (4 set x 12 repetisi)<br>2. Incline Push Up (3 set x 10 repetisi)<br>3. Chest Press menggunakan Dumbbell</html>");
            case "Punggung" -> lblDetailGerakan.setText("<html>Gerakan:<br>1. Pull Up (3 set x 8 repetisi)<br>2. Superman Hold (3 set x 30 detik)</html>");
            case "Kaki" -> lblDetailGerakan.setText("<html>Gerakan:<br>1. Squat (4 set x 15 repetisi)<br>2. Lunges (3 set x 12 repetisi tiap kaki)</html>");
            case "Bahu" -> lblDetailGerakan.setText("<html>Gerakan:<br>1. Overhead Press (4 set x 12 repetisi)<br>2. Lateral Raises (3 set x 15 repetisi)</html>");
            case "Lengan" -> lblDetailGerakan.setText("<html>Gerakan:<br>1. Bicep Curls (4 set x 12 repetisi)<br>2. Tricep Extensions (3 set x 12 repetisi)<br>3. Forearm Wrist Curls (3 set x 15 repetisi)</html>");
            case "Perut" -> lblDetailGerakan.setText("<html>Gerakan:<br>1. Crunch (4 set x 20 repetisi)<br>2. Plank (3 set x 60 detik)</html>");
            default -> {
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudulLatihan = new javax.swing.JLabel();
        lblDetailGerakan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudulLatihan.setText("judul latihan");

        lblDetailGerakan.setText("detail gerakan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDetailGerakan)
                    .addComponent(lblJudulLatihan))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblJudulLatihan)
                .addGap(96, 96, 96)
                .addComponent(lblDetailGerakan)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormDetailWorkout().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDetailGerakan;
    private javax.swing.JLabel lblJudulLatihan;
    // End of variables declaration//GEN-END:variables
}
