/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author musta
 */
public class FormRegistrasi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormRegistrasi.class.getName());

    /**
     * Creates new form FormRegistrasi
     */
    public FormRegistrasi() {
        initComponents();
        setResizable(false); 
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TxtRegNama = new javax.swing.JTextField();
        TxtNamaLengkap = new javax.swing.JLabel();
        TxtRegPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        TxtRegTglLahir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtRegEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtRegBerat = new javax.swing.JTextField();
        TxtRegTinggi = new javax.swing.JTextField();
        BtnSubmitReg = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblBackrgoundReg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("FitLifePro");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 310, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Silakan lengkapi formulir pendaftaran di bawah ini \nuntuk menjadi member resmi.");
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 10));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 610, 50));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        jPanel1.add(TxtRegNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 130, -1));

        TxtNamaLengkap.setText("Nama Lengkap");
        jPanel1.add(TxtNamaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        TxtRegPassword.addActionListener(this::TxtRegPasswordActionPerformed);
        jPanel1.add(TxtRegPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 130, -1));

        jLabel5.setText("Tanggal Lahir");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        TxtRegTglLahir.addActionListener(this::TxtRegTglLahirActionPerformed);
        jPanel1.add(TxtRegTglLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 130, -1));

        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        TxtRegEmail.addActionListener(this::TxtRegEmailActionPerformed);
        jPanel1.add(TxtRegEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 130, -1));

        jLabel7.setText("Berat(kg)");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel8.setText("Tinggi(cm)");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        TxtRegBerat.addActionListener(this::TxtRegBeratActionPerformed);
        jPanel1.add(TxtRegBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 130, -1));
        jPanel1.add(TxtRegTinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 130, -1));

        BtnSubmitReg.setText("Daftar Sekarang");
        BtnSubmitReg.addActionListener(this::BtnSubmitRegActionPerformed);
        jPanel1.add(BtnSubmitReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        jLabel9.setText("(dd/mm/yyyy)");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 360, 390));

        lblBackrgoundReg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBackrgoundReg.setForeground(new java.awt.Color(255, 255, 255));
        lblBackrgoundReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/regist.png"))); // NOI18N
        lblBackrgoundReg.setText("Langkah awal menuju tubuh ideal. Silakan lengkapi formulir pendaftaran di bawah ini untuk menjadi member resmi.");
        lblBackrgoundReg.setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().add(lblBackrgoundReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtRegPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRegPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRegPasswordActionPerformed

    private void TxtRegTglLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRegTglLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRegTglLahirActionPerformed

    private void TxtRegEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRegEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRegEmailActionPerformed

    private void TxtRegBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRegBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRegBeratActionPerformed

    private void BtnSubmitRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubmitRegActionPerformed
        // 1. Mengambil nilai dari semua textfield
    String nama = TxtRegNama.getText().trim();
    String password = new String(TxtRegPassword.getPassword()).trim(); 
    String tanggalLahir = TxtRegTglLahir.getText().trim();
    String email = TxtRegEmail.getText().trim();
    String beratStr = TxtRegBerat.getText().trim();
    String tinggiStr = TxtRegTinggi.getText().trim();

    // 2. Validasi Form Kosong
    if (nama.isEmpty() || password.isEmpty() || tanggalLahir.isEmpty() || 
        email.isEmpty() || beratStr.isEmpty() || tinggiStr.isEmpty()) {
        
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Semua kolom harus diisi! Tidak boleh ada yang kosong.", 
            "Peringatan", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 3. Validasi Format Tanggal Lahir (dd/MM/yyyy)
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
    sdf.setLenient(false); 
    try {
        java.util.Date tgl = sdf.parse(tanggalLahir);
    } catch (java.text.ParseException e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Format Tanggal Lahir salah!\nHarap gunakan format: Hari/Bulan/Tahun (Contoh: 17/08/2004)", 
            "Error Input", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return; 
    }

    // 4. Validasi Angka untuk Berat dan Tinggi
    double berat = 0;
    double tinggi = 0;
    try {
        berat = Double.parseDouble(beratStr);
        tinggi = Double.parseDouble(tinggiStr);
        
        if (berat <= 0 || tinggi <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Berat dan Tinggi harus lebih dari 0!", 
                "Error Input", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Kolom Berat dan Tinggi harus diisi dengan angka!", 
            "Error Input", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 5. JIKA SEMUA VALIDASI LOLOS -> SIMPAN KE DATABASE
    try {
        // Panggil class koneksi (Pastikan kamu sudah buat class DatabaseConnection di package 'koneksi')
        java.sql.Connection conn = DatabaseConnection.getKoneksi();
        
        String sql = "INSERT INTO members (nama, password, tanggal_lahir, email, berat, tinggi) VALUES (?, ?, ?, ?, ?, ?)";
        java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
        
        pstmt.setString(1, nama);
        pstmt.setString(2, password);
        pstmt.setString(3, tanggalLahir);
        pstmt.setString(4, email);
        pstmt.setDouble(5, berat);
        pstmt.setDouble(6, tinggi);
        
        // Eksekusi query
        pstmt.executeUpdate();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Pendaftaran Berhasil! Silakan Login.");
        
        // Pindah ke form login
        FormLogin login = new FormLogin();
        login.setVisible(true);
        this.dispose();
        
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error menyimpan ke database: " + e.getMessage(), 
            "Error Database", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BtnSubmitRegActionPerformed
    
    //private void BtnSubmitRegActionPerformed(java.awt.event.ActionEvent evt) {                                             
        //FormLogin login = new FormLogin();
        //login.setVisible(true);
        //this.dispose();
    //}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormRegistrasi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSubmitReg;
    private javax.swing.JLabel TxtNamaLengkap;
    private javax.swing.JTextField TxtRegBerat;
    private javax.swing.JTextField TxtRegEmail;
    private javax.swing.JTextField TxtRegNama;
    private javax.swing.JPasswordField TxtRegPassword;
    private javax.swing.JTextField TxtRegTglLahir;
    private javax.swing.JTextField TxtRegTinggi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackrgoundReg;
    // End of variables declaration//GEN-END:variables
}
