/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author UsmanEffendi
 */
public class FormPembayaran extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPembayaran.class.getName());

    /**
     * Creates new form FormPembayaran
     */
    
    private String namaKelas;
    private int idMemberAktif;
    public FormPembayaran() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }
    
    public FormPembayaran(String namaMember, String kelas, String jam, String pelatih) {
        initComponents();
        setLocationRelativeTo(null);
        this.namaKelas = kelas;
        this.idMemberAktif = FormLogin.idUserYangLogin;
        
        lblNamaMember.setText("Member: " + namaMember);
        lblDetailKelas.setText("Booking: " + kelas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNamaMember = new javax.swing.JLabel();
        lblDetailKelas = new javax.swing.JLabel();
        cmbMetodeBayar = new javax.swing.JComboBox<>();
        btnKonfirmasi = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNamaMember.setBackground(new java.awt.Color(255, 255, 255));
        lblNamaMember.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblNamaMember.setForeground(new java.awt.Color(51, 204, 255));
        lblNamaMember.setText("Member");
        getContentPane().add(lblNamaMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        lblDetailKelas.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblDetailKelas.setForeground(new java.awt.Color(51, 204, 255));
        lblDetailKelas.setText("Booking");
        getContentPane().add(lblDetailKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        cmbMetodeBayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transfer bank", "Gopay", "Dana", "Qris" }));
        cmbMetodeBayar.addActionListener(this::cmbMetodeBayarActionPerformed);
        getContentPane().add(cmbMetodeBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        btnKonfirmasi.setText("Bayar");
        btnKonfirmasi.addActionListener(this::btnKonfirmasiActionPerformed);
        getContentPane().add(btnKonfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 320, -1));

        btnBatal.setText("Batal");
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 320, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 204, 255));
        jLabel2.setText("<-");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/payment2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMetodeBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMetodeBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMetodeBayarActionPerformed

    private void btnKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiActionPerformed
        try {
        java.sql.Connection conn = DatabaseConnection.getKoneksi();
        
        // =========================================================================
        // 1. AMBIL DATA DARI TABEL 'members'
        // =========================================================================
        // Menggunakan nama kolom yang sesuai dengan gambarmu: nama, email, berat, tinggi
        String sqlCariMember = "SELECT nama, email, berat, tinggi, id_member "
                             + "FROM members WHERE id_member = ?"; 
                             
        java.sql.PreparedStatement pstCari = conn.prepareStatement(sqlCariMember);
        pstCari.setInt(1, FormLogin.idUserYangLogin); 
        java.sql.ResultSet rs = pstCari.executeQuery();
        
        String namaDb = "";
        String emailDb = "";
        double beratDb = 0.0;
        double tinggiDb = 0.0;
        String idMemberDb = "";
        
        if (rs.next()) {
            namaDb = rs.getString("nama"); 
            emailDb = rs.getString("email");
            beratDb = rs.getDouble("berat");
            tinggiDb = rs.getDouble("tinggi");
            // Ubah int dari database menjadi String untuk constructor MemberVIP
            idMemberDb = String.valueOf(rs.getInt("id_member")); 
        }
        
        // Buat objek MemberVIP dengan data asli dari database
        models.MemberVIP member = new models.MemberVIP(namaDb, emailDb, beratDb, tinggiDb, idMemberDb);
        
        // =========================================================================
        // 2. SIMPAN DATA KE TABEL 'pembayaran'
        // =========================================================================
        // Sesuai dengan kolom di tabel pembayaran: id_member, pilihan_kelas, metode_pembayaran
        String sqlBayar = "INSERT INTO pembayaran (id_member, pilihan_kelas, metode_pembayaran) VALUES (?, ?, ?)";
        java.sql.PreparedStatement pstBayar = conn.prepareStatement(sqlBayar);
        
        String kelas = this.namaKelas; 
        String metode = cmbMetodeBayar.getSelectedItem().toString(); 
        
        pstBayar.setInt(1, FormLogin.idUserYangLogin); 
        pstBayar.setString(2, kelas);
        pstBayar.setString(3, metode);
        
        pstBayar.executeUpdate(); // Eksekusi simpan
        
        // =========================================================================
        // 3. TAMPILKAN POP-UP HASIL OVERLOADING
        // =========================================================================
        // Panggil method bookingKelas, pesannya sekarang menggunakan nama asli dari DB
        String pesanOverloading = member.bookingKelas(kelas); 
        
        String pesanAkhir = "Pembayaran berhasil disimpan!\n\n" + pesanOverloading;
        javax.swing.JOptionPane.showMessageDialog(this, pesanAkhir);
        
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error Database: " + e.getMessage());
    }
    }//GEN-LAST:event_btnKonfirmasiActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        FormDashboard awal = new FormDashboard();
        awal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPembayaran().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnKonfirmasi;
    private javax.swing.JComboBox<String> cmbMetodeBayar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDetailKelas;
    private javax.swing.JLabel lblNamaMember;
    // End of variables declaration//GEN-END:variables
}
