/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author UsmanEffendi
 */
public class MenuWorkout extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuWorkout.class.getName());

    /**
     * Creates new form MenuWorkout
     */
    public MenuWorkout() {
        initComponents();
        setResizable(false); 
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Kaki = new javax.swing.JButton();
        Dada = new javax.swing.JButton();
        Bahu = new javax.swing.JButton();
        Lengan = new javax.swing.JButton();
        Punggung = new javax.swing.JButton();
        Perut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Menu Workout Personal Anda");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        Kaki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/kaki.png"))); // NOI18N
        Kaki.setText("jButton1");
        Kaki.setBorderPainted(false);
        Kaki.setContentAreaFilled(false);
        Kaki.addActionListener(this::KakiActionPerformed);
        getContentPane().add(Kaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 1110, 100));

        Dada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/dada.png"))); // NOI18N
        Dada.setText("jButton1");
        Dada.setBorderPainted(false);
        Dada.setContentAreaFilled(false);
        Dada.addActionListener(this::DadaActionPerformed);
        getContentPane().add(Dada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 1110, 100));

        Bahu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/bahu.png"))); // NOI18N
        Bahu.setText("jButton1");
        Bahu.setBorderPainted(false);
        Bahu.setContentAreaFilled(false);
        Bahu.addActionListener(this::BahuActionPerformed);
        getContentPane().add(Bahu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 1100, 100));

        Lengan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/bisep&trisep.png"))); // NOI18N
        Lengan.setText("jButton1");
        Lengan.setBorderPainted(false);
        Lengan.setContentAreaFilled(false);
        Lengan.addActionListener(this::LenganActionPerformed);
        getContentPane().add(Lengan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 1090, 100));

        Punggung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/punggung.png"))); // NOI18N
        Punggung.setText("jButton1");
        Punggung.setBorderPainted(false);
        Punggung.setContentAreaFilled(false);
        Punggung.addActionListener(this::PunggungActionPerformed);
        getContentPane().add(Punggung, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 1090, 100));

        Perut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/perut.png"))); // NOI18N
        Perut.setText("jButton1");
        Perut.setBorderPainted(false);
        Perut.setContentAreaFilled(false);
        Perut.addActionListener(this::PerutActionPerformed);
        getContentPane().add(Perut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 1110, 100));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("<-");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vidio dashboard.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1650, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KakiActionPerformed
        FormDetailWorkout detail = new FormDetailWorkout();
        detail.setJenisLatihan("Kaki");
        detail.setVisible(true);        
        this.dispose();
    }//GEN-LAST:event_KakiActionPerformed

    private void DadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DadaActionPerformed
        FormDetailWorkout detail = new FormDetailWorkout();
        detail.setJenisLatihan("Dada");
        detail.setVisible(true);        
        this.dispose();
    }//GEN-LAST:event_DadaActionPerformed

    private void BahuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BahuActionPerformed
        FormDetailWorkout detail = new FormDetailWorkout();
        detail.setJenisLatihan("Bahu");
        detail.setVisible(true);        
        this.dispose();
    }//GEN-LAST:event_BahuActionPerformed

    private void LenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LenganActionPerformed
        FormDetailWorkout detail = new FormDetailWorkout();
        detail.setJenisLatihan("Lengan");
        detail.setVisible(true);        
        this.dispose();
    }//GEN-LAST:event_LenganActionPerformed

    private void PunggungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PunggungActionPerformed
        FormDetailWorkout detail = new FormDetailWorkout();
        detail.setJenisLatihan("Punggung");
        detail.setVisible(true);        
        this.dispose();
    }//GEN-LAST:event_PunggungActionPerformed

    private void PerutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerutActionPerformed
        FormDetailWorkout detail = new FormDetailWorkout();
        detail.setJenisLatihan("Perut");
        detail.setVisible(true);        
        this.dispose();
    }//GEN-LAST:event_PerutActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        FormDashboard dashboard = new FormDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuWorkout().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bahu;
    private javax.swing.JButton Dada;
    private javax.swing.JButton Kaki;
    private javax.swing.JButton Lengan;
    private javax.swing.JButton Perut;
    private javax.swing.JButton Punggung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
